name: Cypress Tests

on:
  workflow_run:
    workflows: ["pages-build-deployment"] 
    types:
      - completed


jobs:
  cypress-run:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }} 
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Cypress run
          uses: cypress-io/github-action@v6
          with:
            record: true
            parallel: true
          env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
